### ISSUE TITLE
Clean up test databases when exiting with Ctrl-C

### ISSUE THREAD

**Issue by albertZhangTJ** [sqlancer/sqlancer#701]
It seems that sqlancer will leave the generated test databases behind when terminated by `^C` from terminal. Maybe consider adding a shutdown hook to clean up the databases when terminated abruptly?

**Comment by mrigger** [comment]
This is deliberate to some degree - if execution fails due to an unexpected error, it might be helpful to be able to inspect the databases (e.g., in case of database corruption that might cause the error). If we add a shutdown hook, we should ensure that it is executed only in case execution terminates normally.

**Comment by albertZhangTJ** [comment]
Oh I get it, thanks prof!
